---
image: centos:centos7

stages:
  - tests

complete-example:
  stage: tests
  tags:
    - docker
    - xxlarge
  only:
    - merge_requests
    - master
  before_script:
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
    - pip install awscli --upgrade --user
    - yum install -y unzip
    - curl -O https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
    - unzip ./terraform_0.12.24_linux_amd64.zip -d /root/.local/bin/
    - export PATH=/root/.local/bin:$PATH
    - aws configure set default.region us-east-1
  script:
    - cd examples/simple
    - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=terraform-aws-jenkins-examples-common.tfstate" -var="name=$CI_COMMIT_REF_NAME-simple"
    - terraform destroy -auto-approve -var="name=$CI_COMMIT_REF_NAME-simple"
    - terraform apply -auto-approve -var="name=$CI_COMMIT_REF_NAME-simple"
    - terraform destroy -auto-approve -var="name=$CI_COMMIT_REF_NAME-simple"
